FROM magento/magento-cloud-docker-php:8.3-cli-1.4.0

ENV PHP_EXTENSIONS bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip redis xsl sodium

RUN npm install -g ci